### ISSUE TITLE
message_size_limit

### ISSUE THREAD

**Issue by jsmelser** [NTTCom-MS/eyp-postfix#44]
So the default message_size_limit in postfix is 10m. We had to update it today but this module does not support it. I forked the module for now.

Either 
A is it possible to add the parameter?
B add a "extra_config" hash array so we can add any extra stuff?
C Both?

**Comment by jordiprats** [comment]
Hi,
I've added this variable in [PR45](https://github.com/NTTCom-MS/eyp-postfix/pull/45)

thanks for suggesting it
