### ISSUE TITLE
change URL at forge.puppet.com

### ISSUE THREAD

**Issue by p4t0k** [NTTCom-MS/eyp-postfix#46]
Hi, this is not related to code itself but to the puppet forge page https://forge.puppet.com/eyp/postfix. Project URL points to your squid project. Please repair it to correct URL: https://github.com/NTTCom-MS/eyp-postfix ;)

**Comment by jordiprats** [comment]
Hi,
I've fixed it by uploading the latest release:

https://forge.puppet.com/eyp/postfix/readme

Thanks for reporting it

regards,
