### ISSUE TITLE
Looks like mastercf.pp is not in the latest release.

### ISSUE THREAD

**Issue by jsmelser** [NTTCom-MS/eyp-postfix#77]
I am using redhat 8 and getting:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Unsupported RHEL/CentOS version! (file: /etc/puppetlabs/code/environments/jsmelser/modules/postfix/manifests/mastercf.pp, line: 474, column: 20) on node drvlopsptr801.trustamerica.com

I am using: mod 'eyp-postfix', '0.2.39'

So I am on the latest release. but it seems like that file, according to source, was change to support redhat 8?

**Comment by jsmelser** [comment]
Ok, looks like .40 in releases has it taken care of, it was just never pushed for forge. Can it be?

**Comment by jordiprats** [comment]
Hi,
Yes, RHEL8 is supported starting 0.1.40 but I did not upload the latest version to the puppet forge.

I have just uploaded version 0.1.41 to the forge

kind regards,

**Comment by jsmelser** [comment]
Awesome, thanks!
